name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "19"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run generate
      - run: pnpm --package=typescript dlx tsc -b
      - uses: changesets/action@v1
        with:
          title: "ci: draft a new release"
          commit: "ci: draft a new release"
          publish: pnpx @changesets/cli publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
