name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npx prettier --check .
  markdownlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npx markdownlint-cli .
  spellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npx cspell lint --relative --no-progress '**'
  publish:
    runs-on: ubuntu-20.04
    needs: ['prettier', 'markdownlint', 'spellcheck']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run publish-to-github
