name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: DimensionDev/github-token-action@latest
        with:
          registry: true
      - run: npm ci
      - run: npx prettier --check .
      - run: npx markdownlint-cli .
      - run: npx cspell '**'
      - run: npm test
      - run: npm run lint
      - run: npm run publish-to-github

